[package]
name = "nimiq-serde"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq helpers for SerDe usage"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
hex = "0.4"
postcard = { git = "https://github.com/nimiq/postcard-bytes", features = ["alloc"] }
serde = "1.0"
serde_derive = "1.0"

nimiq-serde-derive = { path = "derive" }

[dev-dependencies]
nimiq-collections = { workspace = true }
